# Uncomment a line below to enable a "Sponsor" button on the repo.
# See https://docs.github.com/articles/displaying-a-sponsor-button-in-your-repository.

# github: [blaze-uz]
# custom: ["https://blaze.uz/sponsor"]
